### ISSUE TITLE
JMSExpiration should be zero for non-expiring messages

### ISSUE THREAD

**Issue by isae** [rabbitmq/rabbitmq-jms-client#112]
The value for infinite message TTL in RabbitMQ is `null`. 
However, according to [specification](https://docs.oracle.com/cd/E19957-01/816-5904-10/816-5904-10.pdf), page 31), 

> If the time-to-live is specified as zero, expiration is set to zero which indicates
> the message does not expire. 

So, when `RMQMessage#setJMSPropertiesFromAmqpProperties` is called, it does not fill the `JMSExpiration` since message expiration is null. Thus, later invocation of `getJMSExpiration` produces `java.lang.NumberFormatException: Null is not a valid long`.

**Comment by michaelklishin** [comment]
You are welcome to contribute a PR.
