### ISSUE TITLE
new RMQConnectionFactory property is not supported by RMQObjectFactory

### ISSUE THREAD

**Issue by consultantleon** [rabbitmq/rabbitmq-jms-client#117]
Recently declareReplyToDestination property has been added under issue fix #69.
I try to set this property to false (don't even understand why the default is left to true, it's just a bug trying to create a reply-to queue!?), but the ConnectionFactory setup seems to ignore my config
declareReplyToDestination=false

Looking at the decompiled code of RMQObjectFactory it's clear why, there's a line missing to setup this cf property!
`public Object createConnectionFactory(Reference ref, Hashtable<?, ?> environment, Name name) throws NamingException {
        this.logger.trace("Creating connection factory ref '{}', name '{}'.", ref, name);
        RMQConnectionFactory f = new RMQConnectionFactory();

        try {
            f.setUri(this.getStringProperty(ref, environment, "uri", true, f.getUri()));
        } catch (JMSException var6) {
            this.logger.warn("Failed to set RMQConnectionFactory properties by URI--defaults taken initially.", var6);
        }

        f.setHost(this.getStringProperty(ref, environment, "host", true, f.getHost()));
        f.setPassword(this.getStringProperty(ref, environment, "password", true, f.getPassword()));
        f.setPort(this.getIntProperty(ref, environment, "port", true, f.getPort()));
        f.setQueueBrowserReadMax(this.getIntProperty(ref, environment, "queueBrowserReadMax", true, f.getQueueBrowserReadMax()));
        f.setOnMessageTimeoutMs(this.getIntProperty(ref, environment, "onMessageTimeoutMs", true, f.getOnMessageTimeoutMs()));
        f.setSsl(this.getBooleanProperty(ref, environment, "ssl", true, f.isSsl()));
        f.setTerminationTimeout(this.getLongProperty(ref, environment, "terminationTimeout", true, f.getTerminationTimeout()));
        f.setUsername(this.getStringProperty(ref, environment, "username", true, f.getUsername()));
        f.setVirtualHost(this.getStringProperty(ref, environment, "virtualHost", true, f.getVirtualHost()));
        f.setCleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose(this.getBooleanProperty(ref, environment, "cleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose", true, f.isCleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose()));
        return f;
    }`

**Comment by michaelklishin** [comment]
@consultantleon please submit a PR?

**Comment by consultantleon** [comment]
Hi Michael,
I'm not sure how to push to a new branch in this repo? Haven't contributed
to a github project before :$

I made the patch and tested it with my application and confirmed that it
works (can't seem to run the tests as I'm on windows and do not have make
binary installed, at least not on the default path)

Index: src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java (date
1567020635000)
+++ src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java (date
1567040179000)
@@ -202,6 +202,7 @@
         f.setUsername           (getStringProperty (ref, environment,
"username",            true, f.getUsername()           ));
         f.setVirtualHost        (getStringProperty (ref, environment,
"virtualHost",         true, f.getVirtualHost()        ));

 f.setCleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose(getBooleanProperty(ref,
environment, "cleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose",
              true,
f.isCleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose()
    ));
+        f.setDeclareReplyToDestination(getBooleanProperty(ref,
environment, "declareReplyToDestination", true, true));

         return f;
     }

If you explain how I can push my changes to a branch I'll do so and create
a PR,
Regards

Leon

**Comment by michaelklishin** [comment]
Pasting the diff here since GitHub seems to refuse to format it in a comment posted over email:

``` diff
Index: src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
--- src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java (date
1567020635000)
+++ src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java (date
1567040179000)
@@ -202,6 +202,7 @@
         f.setUsername           (getStringProperty (ref, environment,
"username",            true, f.getUsername()           ));
         f.setVirtualHost        (getStringProperty (ref, environment,
"virtualHost",         true, f.getVirtualHost()        ));

 f.setCleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose(getBooleanProperty(ref,
environment, "cleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose",
              true,
f.isCleanUpServerNamedQueuesForNonDurableTopicsOnSessionClose()
    ));
+        f.setDeclareReplyToDestination(getBooleanProperty(ref,
environment, "declareReplyToDestination", true, true));

         return f;
     }
```

**Comment by michaelklishin** [comment]
@consultantleon you cannot push to this repository, sorry. You can fork it and push to your fork, and then submit a pull request from there. See [Creating a pull request from a fork](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) in GitHub docs. There's a [3rd party tutorial](https://yangsu.github.io/pull-request-tutorial/) as well.

Thank you!

**Comment by acogoluegnes** [comment]
@consultantleon I added the property to `RMQObjectFactory` in 34a20f9, thanks for pointing this out!

**Comment by acogoluegnes** [comment]
@consultantleon [1.13.0.RC1 has been released](https://groups.google.com/d/msg/rabbitmq-users/SirwVE_wVns/3bpml05fAQAJ) with the fix if you want to give it a try.
