### ISSUE TITLE
Lost publisher confirm callbacks when close session immediately after sent message

### ISSUE THREAD

**Issue by feelyou** [rabbitmq/rabbitmq-jms-client#119]
When I sent 10 messages and immediately close the session, the publisher confirm listener method would not be called. If I make the thread sleep for 10ms or more, The listener method is called properly. It maybe need some cleanup when closing the session.

**Comment by michaelklishin** [comment]
This sounds right to me: those messages have never made it to the broker and thus cannot be confirmed.

**Comment by michaelklishin** [comment]
In other words, a published message is not guaranteed to get a confirm: the data can be lost in flight (in a TCP buffer the kernel is about to clear, for example) and neither RabbitMQ nor the client can detect it. This is where timeouts for confirmations come in and it's up to applications developers to integrate them depending on [what publisher confirm strategy](https://www.rabbitmq.com/publishers.html#data-safety) they use.

**Comment by acogoluegnes** [comment]
Publisher confirms didn't have time to come (they're asynchronous), so the listener method is not called. If you want to avoid this, you may want to change your code to synchronize the confirm listener and the closing (avoiding to close if there are outstanding confirms). I think this is too opinionated to be the default in the library.

This is [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) material BTW.
