### ISSUE TITLE
rabbitmq-jms 'admin' objects RMQConnectionFactory and RMQDestination are not compatible with RMQObjectFactory

### ISSUE THREAD

**Issue by l-k-test** [rabbitmq/rabbitmq-jms-client#128]
RMQConnectionFactory.getReference() and RMQDestination.getReference() return javax.naming.Reference instances that are not 'convertible' back to RMQConnectionFactory/RMQDestination.

There are 2 problems:

1. The javax.naming.Reference instances do not have 'classFactory' property set. As a result an instance of RMQConnectionFactory/RMQDestination can be bound into a naming context. But it cannot be retrieved back from JNDI. Instead an instance of javax.naming.Reference is retrieved.

2. Even if RMQObjectFactory is used as 'classFactory' in javax.naming.Reference instances, it is still not going to work. The reason is: RMQConnectionFactory/RMQDestination use their class names as 'className' property of javax.naming.Reference. RMQObjectFactory  does not recognize these class names as valid. This class has the following comment (and the code that does what the comment says):
```
        /*
         * Valid class names are:
         * javax.jms.ConnectionFactory
         * javax.jms.QueueConnectionFactory
         * javax.jms.TopicConnectionFactory
         * javax.jms.Topic
         * javax.jms.Queue
         *
         */

```

**Comment by michaelklishin** [comment]
@l-k-test so what would you suggest the client do?

**Comment by l-k-test** [comment]
Well:
1. Make sure RMQObjectFactory recognizes RMQConnectionFactory and RMQDestination as valid 'className' properties and invokes internally createConnectionFactory() for RMQConnectionFactory class name and createDestination() for RMQDestination class name. Alternatively use one of already valid javax.jms.XYZ class names instead of RMQConnectionFactory/RMQDestination.
2. Change RMQConnectionFactory.getReference() and RMQDestination.getReference(): use Reference(String className, String factory, String factoryLocation) contrructor and pass RMQObjectFactory class name as the second parameter.
3. Maybe more properties must be added to javax.naming.Reference instances returned from RMQConnectionFactory.getReference() and RMQDestination.getReference(). Here I am not absolutely sure: maybe it is already good enough.

**Comment by acogoluegnes** [comment]
@l-k-test you're welcome to have a look at https://github.com/rabbitmq/rabbitmq-jms-client/pull/130 and comment!
