### ISSUE TITLE
Ability to provide multiple hosts to RMQObjectFactory

### ISSUE THREAD

**Issue by arthurKahn** [rabbitmq/rabbitmq-jms-client#140]
The fix for #50  allow us to provide multiple hosts using RMQConnectionFactory. I think it make sense to report those changes in  RMQObjectFactory so we can specify multiple hosts using JNDI.

**Comment by michaelklishin** [comment]
@acogoluegnes do you understand what's being asked for here?

**Comment by acogoluegnes** [comment]
@michaelklishin I think it means adding `uris` in the list of [supported properties](https://github.com/rabbitmq/rabbitmq-jms-client/blob/6bf7e7f71b2ae28f9efdd8c26db9e0d4ff8cb7ac/src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java#L195-L212) in RMQObjectFactory. Am I right @arthurKahn?

If yes, I think it's indeed possible to support this property to be able to specify a set of URIs separated by commas.

**Comment by arthurKahn** [comment]
Hi @acogoluegnes,
Yes adding the support of `uris` is one of the option, the other is to be able to add multiple `host / port`

**Comment by acogoluegnes** [comment]
Using `uris` would be simpler, because it translates directly to the property added in #50. This is trivial, PRs are always welcome.

**Comment by acogoluegnes** [comment]
@arthurKahn [RabbitMQ JMS Client 2.4.0.RC1](https://groups.google.com/g/rabbitmq-users/c/SAgLco4ysRw/m/mhRc1BAACgAJ) with the change is available for testing. 2.4.0 should follow in a couple of weeks.
