### ISSUE TITLE
Plans for non-JMS RabbitMQ topic AMQP 0-9-1 interoperability support?

### ISSUE THREAD

**Issue by theangrydev** [rabbitmq/rabbitmq-jms-client#142]
I noticed the following note in the [documentation](https://www.rabbitmq.com/jms-client.html):

> An interoperability feature allows you to define JMS 'amqp' destinations that read and/or write to non-JMS RabbitMQ resources. Note this feature does not support JMS topics.

Are there plans to add support for AMQP topic interoperability too?

**Comment by michaelklishin** [comment]
This client or the plugin it relies on won't be our team's priority for the foreseeable future, so I guess the answer is "no".
