### ISSUE TITLE
Add queueDeclareArguments parameter to RMQDestination

### ISSUE THREAD

**Issue by markus-mueller-br** [rabbitmq/rabbitmq-jms-client#143]
Hello,

would it be possible to add a queueDeclareArguments parameter to RMQDestinations?

The only way to set queue arguments I see so far is through casting the JMSSession to a RMQSession and setting queueDeclareArguments, but I don't see how we can do that before the creation of a Queue.

I feel like it would be easier to offer a parameter in RMQDestinations that is merged with queueDeclareArguments in declareRMQQueue before the channel.queueDeclare: https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/src/main/java/com/rabbitmq/jms/client/RMQSession.java#L928-L932 .

The use case would be to be able to create Quorum Queues, which can't be done through RabbitMQ policies.

**Comment by acogoluegnes** [comment]
@markus-mueller-br [RabbitMQ JMS Client 2.4.0.RC1](https://groups.google.com/g/rabbitmq-users/c/SAgLco4ysRw/m/mhRc1BAACgAJ) with the change is available for testing. 2.4.0 should follow in a couple of weeks.
