### ISSUE TITLE
Boolean properties do not work when working with AMQP destinations

### ISSUE THREAD

**Issue by wengertj** [rabbitmq/rabbitmq-jms-client#146]
Hello,

in our project we noticed that `rabbitmq-jms` will silently fail to read boolean properties or more specifically `RMQMessage#getBooleanProperty` will always return false.

I've created a [minimal working example](https://github.com/wengertj/rabbitmq-jms-booleanprops/blob/main/src/test/java/com/github/wengertj/RabbitMQJmsBooleanHeaderTest.java#L96) which demonstrates the problem.

It seems that the fix is rather simple: "just" handle `Boolean` in [RMQMessage#putIfNotNullAndAmqpType](https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/src/main/java/com/rabbitmq/jms/client/RMQMessage.java#L1036). I've tried this out locally and the example will not fail anymore.

Is there a specific reason why `Boolean` is not handled or was this simply a mistake? 

I'd be happy to provide a PR!

Thanks 👍

**Comment by michaelklishin** [comment]
@wengertj please do provide a PR and we will discuss it. Thank you.

**Comment by wengertj** [comment]
Thanks again for responding so quickly ! 

Do you already have an (approximate) release time frame for 2.4.0 @michaelklishin ?

**Comment by acogoluegnes** [comment]
Fixed by #147.

**Comment by acogoluegnes** [comment]
@wengertj We are planning on releasing 2.4.0.RC1 by the end of the week.

**Comment by acogoluegnes** [comment]
@wengertj [RabbitMQ JMS Client 2.4.0.RC1](https://groups.google.com/g/rabbitmq-users/c/SAgLco4ysRw/m/mhRc1BAACgAJ) is available with the change for testing. 2.4.0 should follow in a couple of weeks.
