### ISSUE TITLE
Not a code defect - but is there a CI process now?

### ISSUE THREAD

**Issue by chiragsanghavi** [rabbitmq/rabbitmq-jms-client#151]
readme.md has a link to https://travis-ci.org/rabbitmq/rabbitmq-jms-client - but travis-ci.org is no longer valid. Is there a new CI process now and should link be updated?

**Comment by chiragsanghavi** [comment]
if CI process is no longer application; I can submit a PR to remove old link.

**Comment by acogoluegnes** [comment]
We have our own CI instance, but I'm not sure it supports tags. You can indeed submit a PR to remove the old link. I'll see if I can set up a GitHub Actions flow to test the JMS client, the main problem being TLS tests, but it should be possible to skip them.

**Comment by acogoluegnes** [comment]
I set up a GitHub Actions flow to run the test suite and added the build status tag on the readme page. Thanks for pointing this out.
