### ISSUE TITLE
RMQMessageProducer setting text/plain content type for TextMessage

### ISSUE THREAD

**Issue by amitkapps** [rabbitmq/rabbitmq-jms-client#19]
In case the destination is amqp and the jms message is a TextMessage, could the RMQMessageProducer publish the AMQP message with content type text/plain?

Its currently set as application/octet stream for both TextMessage and BytesMessage.

**Comment by michaelklishin** [comment]
It's generally up to applications to set and interprete content type. @acogoluegnes thoughts?

**Comment by acogoluegnes** [comment]
@amitkapps I understand `text/plain` would make more sense for `TextMessage`s, but as @michaelklishin suggested, applications should set and interpret the content type. Does it make sense the JMS client sets `text/plain` while the message actually carries JSON?

The sending application could set the content type on the JMS message:

```java
TextMessage msg = session.createTextMessage("Hello world");
msg.setStringProperty("content-type", "text/plain");
```

An AMQP receiver could then get the content type from the headers:

```
public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body) throws IOException {
  properties.getHeaders().get("content-type");
}
```

**Comment by michaelklishin** [comment]
The JSON point is a very good one. I don't think we should do it.

**Comment by amitkapps** [comment]
@acogoluegnes @michaelklishin thanks for the feedback.
This would work, however it requires changes both on the client jms side as well as, say, an amqp receiver. 
Currently, if I were to set the stringProperty content-type text/plain on the jms producer side, it would not make the amqp consumer think its a text messages since the contentType property on the amqp message is always being hardcoded as application/octet-stream.

It would help with jms > ampq interoperability. Otherwise you're forced to handle that differently on the consumer side, whereas the amqp spec already provides first class support for MIME types with basic.content-type property string.

**Comment by michaelklishin** [comment]
Unfortunately we cannot assume that every `TextMessage` actually contains text (and not a text-based encoded values as in the JSON example above).

**Comment by amitkapps** [comment]
How about ability to transparently map some set of incoming jms headers to amqp headers. 
E.g. case in point, if a jms header String property comes in as content-type that could get mapped to the equivalent AMQP header.
A similar strategy could possible also apply to other header properties as well.

**Comment by michaelklishin** [comment]
This is not a venue for discussions. Smarter is not always better when it comes to libraries. Just set the damn field.

**Comment by amitkapps** [comment]
_Not meant for discussions_ really? 
great argument. Moving on....

**Comment by michaelklishin** [comment]
@amitkapps yes, really. Discussions belong to the mailing list. That's how our team operates, whether you like it or not. Sorry not sorry.
