### ISSUE TITLE
RMQObjectFactory does not work with Wildfly object-factory JNDI binding

### ISSUE THREAD

**Issue by remibantos** [rabbitmq/rabbitmq-jms-client#21]
The RMQObjectFactory class does not work with Wildfly object-factory JNDI binding configuration, documented [here](https://docs.jboss.org/author/display/WFLY10/JNDI+Reference)
This is because the [getObjectInstance()](https://docs.oracle.com/javase/7/docs/api/javax/naming/spi/ObjectFactory.html#getObjectInstance(java.lang.Object,%20javax.naming.Name,%20javax.naming.Context,%20java.util.Hashtable)) Object first argument is handled as a [javax.naming.Reference](https://docs.oracle.com/javase/7/docs/api/javax/naming/Reference.html) instance whereas a java.lang.String object is actually provided to this method by Wildfly when using the [object-factory](https://docs.jboss.org/author/display/WFLY10/JNDI+Reference) binding configuration.
Thus, the following NamingException is always thrown by this code bellow:
```
Reference ref = obj instanceof Reference ? (Reference) obj : null;

        if (ref == null && (environment == null || environment.isEmpty())) {
            throw new NamingException("Unable to instantiate object: obj is not a Reference instance and environment table is empty");
        }
```

From what I understand from [javax.naming.ObjectFactory](https://docs.oracle.com/javase/7/docs/api/javax/naming/spi/ObjectFactory.html) javadoc, there is not requirement to deal with this parameter as a [javax.naming.Reference](https://docs.oracle.com/javase/7/docs/api/javax/naming/Reference.html) instance only.
So in order to make the RMQObjectFactory work with Wildfly object-factory, we could add the possibility to provide all required properties via the Hashtable<?,?> environment third argument of [getObjectInstance()](https://docs.oracle.com/javase/7/docs/api/javax/naming/spi/ObjectFactory.html#getObjectInstance(java.lang.Object,%20javax.naming.Name,%20javax.naming.Context,%20java.util.Hashtable)) method.

Note that I'm going to propose a PR for that.

**Comment by michaelklishin** [comment]
@remibantos sure, thank you.

Holy cow, there are still widely used APIs that use Hashtables? TIL.

**Comment by remibantos** [comment]
I would say that javax.naming.ObjectFactory has not evolved very much since a very long time :)
