### ISSUE TITLE
Properties set on messages should override those on publisher

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-jms-client#26]
See [this rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/ngO62VshH2o), originally posted as a question in #25.

Doing it the other way around seems odd. I cannot think of a reason for that.

@acogoluegnes @artembilan @garyrussell perhaps you can?

**Comment by garyrussell** [comment]
I concur; I would expect the hierarchy to be 

- method argument (in overloaded `send()`)
  - existing message properties
     - producer defaults

However, it's tough to make a behavior change like that in a maintenance release.

We (Spring) typically handle cases like that with a boolean that retains the previous behavior in the current release and switches to the new behavior in the next release.

That avoids breaking existing apps that are leveraging the current behavior.

**Comment by michaelklishin** [comment]
We can do it in 2.0 or introduce a swappable strategy for property merging.

**Comment by acogoluegnes** [comment]
Well, according to the JMS specification, the current behavior is correct, e.g. for `JMSPriority`:

> When a message is sent, this field is ignored. After completion of the send, it holds the value specified by the method sending the message.

And the Javadoc:

> This method is for use by JMS providers only to set this field when a message is sent. This message cannot be used by clients to configure the priority level of the message.

Same thing for expiration and delivery mode.

I suggest we keep this behavior as the default one, but provide a flag to switch to non-compliant but more natural behavior.

cc @michaelklishin @garyrussell @damonsutherland
