### ISSUE TITLE
Content_type needs to be configurable

### ISSUE THREAD

**Issue by mcgiri** [rabbitmq/rabbitmq-jms-client#42]
The content_type in RMQMessageProducer file is hardcoded to application/octet-stream for text messages. So even when the application supplies a content_type, this configuration overrides the one supplied. Is there a way to make it configurable like using the content_type from the header if its already set else set it?

Reported on [`rabbitmq-users`](https://groups.google.com/d/topic/rabbitmq-users/mxYE6VkrjYI/discussion)

**Comment by acogoluegnes** [comment]
@mcgiri Here's a workaround: https://github.com/rabbitmq/rabbitmq-jms-client/issues/19#issuecomment-281280214

**Comment by acogoluegnes** [comment]
There's no standard content type header in JMS. The best we can do is to provide an interface to customize the `AMQP.BasicProperties.Builder`:

```java
public interface AmqpPropertiesCustomizer {
  AMQP.BasicProperties.Builder customize(AMQP.BasicProperties.Builder builder, Message jmsMessage);
}
```

Your implementation could be the following:

```java
public class ContentTypeAmqpPropertiesCustomizer implements AmqpPropertiesCustomizer {

  public AMQP.BasicProperties.Builder customize(AMQP.BasicProperties.Builder builder, Message jmsMessage) {
    String contentType = jmsMessage.getStringProperty("content_type");
    if (contentType != null) {
      builder.contentType(contentType);
    }
    return builder;
  }

}
```

The customizer instance would be set at the `RMQConnectionFactory` level. @mcgiri Would that work for you?

**Comment by mcgiri** [comment]
@acogoluegnes  -- Apologies, i am going to take couple of days to get back since I am calling it from an app which uses native JMS methods, and I need to look at options to use the interface. I guess it should work but let me come back.

**Comment by mcgiri** [comment]
@acogoluegnes -- Even with the interface, the content_type would still be set to "application/octet-stream" right? Is there a way to not set it at all?

**Comment by michaelklishin** [comment]
As far as I can tell, [that is the case](https://github.com/rabbitmq/rabbitmq-jms-client/search?utf8=✓&q=application%2Foctet-stream&type=). It's certainly possible to have that field blank in the underlying Java client, though.

**Comment by acogoluegnes** [comment]
@mcgiri The customizer would be applied after, so it could override the previous value of `content_type`.

**Comment by mcgiri** [comment]
@acogoluegnes Can you please include the interface? I should be able to use it. Sorry for the delay again. Thanks!

**Comment by acogoluegnes** [comment]
@mcgiri [1.9.0.RC1](https://groups.google.com/d/msg/rabbitmq-users/24AI3MDK3Mo/RsZ2WYaACQAJ) has shipped with this feature, you can give it a try.
