### ISSUE TITLE
Support for metrics collection

### ISSUE THREAD

**Issue by ftsang** [rabbitmq/rabbitmq-jms-client#49]
Currently there is no way to configure the connection factory to turn metrics collection on, even though it is a feature that has been supported by the underlying rabbitmq/amqp connection factory.

Moreover, it would be preferable if the configuration can be done declaratively to facilitate setting them up as resources in JNDI. Presumably, some sort of dynamic class loading is needed for this to work.

**Comment by acogoluegnes** [comment]
Good idea. I'd suggest 2 ways:
 * add a `MetricsCollector` property to `RMQConnectionFactory`. This could be easily set up programmaticaly or with DI container like Spring.
 * add a `ConnectionFactoryPostProcessor` (interface to be defined) property to `RMQConnectionFactory` that would be called after the Java client `ConnectionFactory` instance is created but before it creates a new connection. This would be a useful hook to customize the `ConnectionFactory`, and not only for metrics collection.

Regarding metrics collection when JNDI is used, the `ConnectionFactoryPostProcessor` could be set programmatically after the JNDI look-up. We could also add a `ConnectionFactoryPostProcessorClass` property and the `RMQConnectionFactory` would create the `ConnectionFactoryPostProcessClass` instance itself and it would be applied later on. I'm reluctant to add this JNDI workaround though, I think the 2 properties I suggest above are enough.
