### ISSUE TITLE
Provide a way to configure onMessageTimeoutMs

### ISSUE THREAD

**Issue by gmornet** [rabbitmq/rabbitmq-jms-client#5]
The time allowed for message processing in MessageListener.onMessage(Message) is set to 2 seconds  in `RMQSession` with constant `ON_MESSAGE_EXECUTOR_TIMEOUT_MS`.

For some needs I require a much longer delay while the message is beeing processed on a slow backend. This works well with the Java AMQP client (that doesn't have a time limit on `onMessage`), but not with `rabbitmq-jms-client`.

Therefore, I would like to have `onMessageTimeoutMs` configurable as a JNDI property, as currently done with `queueBrowserReadMax`.

**Comment by michaelklishin** [comment]
Kudos to @gmornet for contributing.
