### ISSUE TITLE
RMQSession.createConsumer(Destination, messageSelector) throws UnsupportedOperationException without checking if destination is a topic

### ISSUE THREAD

**Issue by killermave** [rabbitmq/rabbitmq-jms-client#52]
Hello,
In RMQSession class, the below method checks for empty message selector and throws an exception if found non-empty. This does not take into account whether the destination is Topic(where message selectors are supported) or Queue. 
```
public MessageConsumer createConsumer(Destination destination, String messageSelector) throws JMSException {
illegalStateExceptionIfClosed();
        if (nullOrEmpty(messageSelector)) {
            return createConsumer(destination);
        } else {
            // we are not implementing this method yet
            throw new UnsupportedOperationException();
        }
    }
```

The context is I am using JmsTemplate.receiveSelected with a messageselector on a topic

**Comment by michaelklishin** [comment]
@killermave and what's the suggested behavior and why?

**Comment by killermave** [comment]
Currently the createConsumer method is able to create Queue/Topic Consumers as long as there are no message selectors involved whatsoever. This should be changed to allow message selectors for a Topic which RabbitMQ JMS client supports today.
