### ISSUE TITLE
Uncatchable exception thrown when connecting with an invalid RMQDestination queue. 

### ISSUE THREAD

**Issue by AccountToAskQuestions** [rabbitmq/rabbitmq-jms-client#53]
Hi, I've ran into an issue where when I attempt to set up a message listener on an RMQDestination with an invalid destname the errors can not be caught and instead get thrown I am assuming from SLF4J. The core of the issue is that I need a way to see that an error has occurred on that connection so that I can identify when an invalid queue has been entered. Currently that error will get posted, but to our back end logging, where it will post it multiple times ( due to the persistent nature of AMQP ) and is uncatchable within the code. 

I've tried forcing other errors and everything else is caught before it sets up the message listener or after, an invalid destination name seems to be the only cause of making an uncatchable error. 

This is the exact error I am hitting. 

https://github.com/rabbitmq/rabbitmq-jms-client/blob/master/src/main/java/com/rabbitmq/jms/client/RMQMessageConsumer.java

    GetResponse getFromRabbitQueue() {
        String qN = rmqQueueName();
        try {
            return getSession().getChannel().basicGet(qN, false);
        } catch (Exception e) { // includes unchecked exceptions, e.g. ShutdownSignalException
            if (!(e instanceof ShutdownSignalException) && !(e.getCause() instanceof ShutdownSignalException)) {
                logger.error("basicGet for queue '{}' threw unexpected exception", qN, e);
            }
        }
return null;

**Comment by acogoluegnes** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by acogoluegnes** [comment]
@AccountToAskQuestions Thanks for reporting this. We need more information, like a way to reproduce and what you'd like to do, to make this an actionable item. Please move this to the [https://groups.google.com/forum/#!forum/rabbitmq-users](mailing list). Thanks.

**Comment by acogoluegnes** [comment]
Follow-up thread: https://groups.google.com/d/msg/rabbitmq-users/bOnTPQkg2SM/JQgax-JeCAAJ
